### ISSUE TITLE
px-twoup, px-fourup, px-sixup  not working on IE11

### ISSUE THREAD

**Issue by jvenky68** [PredixDev/px-widget-cards#1]
We tried the on IE11 the px-fourup, px-twoup, px-sixup are not working on IE11

**Comment by jvenky68** [comment]
![ie11px-twoupissue](https://cloud.githubusercontent.com/assets/6218475/12857466/3344bcf0-cbff-11e5-96b3-3c7b58aea539.png)

**Comment by jvenky68** [comment]
added screen shot

**Comment by mdwragg** [comment]
Are you in 'compatibility mode' by any chance?

**Comment by jvenky68** [comment]
![compatibilitymode](https://cloud.githubusercontent.com/assets/6218475/12860605/c22c9128-cc12-11e5-9cd8-82ca59a612a5.png)

**Comment by jvenky68** [comment]
please see the screen shot.

**Comment by mdwragg** [comment]
<img width="1649" alt="screen shot 2016-02-09 at 10 46 39" src="https://cloud.githubusercontent.com/assets/3594714/12926959/7cf28936-cf1a-11e5-9cc4-9127d8773b4d.png">

**Comment by mdwragg** [comment]
Hi, see above - this is from IE11...

**Comment by mdwragg** [comment]
Just tested on a 'real' Windows machine (above was a Windows 8.1 VM). Works on IE11 and Edge.
