### ISSUE TITLE
Customize the Card

### ISSUE THREAD

**Issue by abhilash-shrivastava** [PredixDev/px-widget-cards#3]
Hi,

I just created one px-widget-card for my view services and displaying it in the deck.

It is a threeup card and showing some simple line chart, bar chart etc. by default, so I am assuming its card inside card.

How to customize and where I can change the values displayed by the card

Thanks
Abhilash

**Comment by nonmetalhail** [comment]
Hi, Can you give us some more details and provide us with a gist? Thanks!

**Comment by abhilash-shrivastava** [comment]
I was following the following example and created some card.

https://github.com/PredixDev/predix-seed

In this seed app it displays a widget card with some chart and bar picture inside the card, but  I am not sure where they are putting these value in widget card and how can i change content displaying inside the widget card.

Card currently showing

<img width="785" alt="screen shot 2016-04-13 at 5 59 15 pm" src="https://cloud.githubusercontent.com/assets/13994709/14514013/9d3f87f2-01a1-11e6-9ae4-e11e19a05e4f.png">

I want to change this card according to my app, so i need to know following things:

How to change this by default display of the card?

what is the right way to use this card in the application.

As i do not even know where exactly is this card getting used, so I am not sure what gist you want from my side. 

let me know if you need any other specific information

Thanks

**Comment by randyaskin** [comment]
@abhilash-shrivastava sorry for the huge delay, just looking through old GH issues - were you able to figure out what you needed to accomplish with cards in the seed? The seed is very different now than it was early last year so hopefully it is much easier to understand.
