### ISSUE TITLE
Cant find px-widget-cards.html  !!

### ISSUE THREAD

**Issue by DineshBabuS** [PredixDev/px-widget-cards#7]
Hi, Might be a stupid question. I cant find the px-widget-cards.html file when i clone this code. 
ENOENT: no such file for px-widget-cards.html.

**Comment by DineshBabuS** [comment]
Just saw a better one !  https://github.com/PredixDev/px-sample-cards . thanks!

**Comment by mdwragg** [comment]
Hi @DineshBabuS!

Yeah, there isn't a `px-widget-cards.html` import but individual import for each type of card (taken from the front page/readme of this repo):

> px-widget-cards is a Predix UI component. Use the 'px-twoup', 'px-threeup', 'px-fourup' and 'px-sixup' components to create cards with two, three, four or six components laid out in a grid (see demo.html for usage and running example).

**Comment by DineshBabuS** [comment]
Hi mdwragg, Thanks for your reply.  I think the link rel (to px-widget-cards.html) needs to replaced in the Readme.  Might avoid someone getting the same problem.
