### ISSUE TITLE
The readme file has a wrong command for the polymer-loader.html

### ISSUE THREAD

**Issue by kpashov** [PredixDev/px-widget-cards#8]
Hello,

The instructions on how to use this file read:

> Second, import the component to your application with the following tag in your head.
> 
> `<link rel="import" href="/bower_components/px-widget-cards/px-widget-cards.html"/>`

This results in an error as there is no px-widget-cards.html file.

`Fatal error: ENOENT: no such file or directory, open '/srv/git-tree/predix/predix-rmd-ref-app/rmd-ref-app-ui/public/bower_components/px-widget-cards/px-widget-cards.html`

This should be changed to reflect that there is a separate template for each card:

> Second, import the component to your application with the following tag in your head.
> 
> `<link rel="import" href="/bower_components/px-widget-cards/px-twoup"/>
> ...
> <link rel="import" href="/bower_components/px-widget-cards/px-sixup"/>`

**Comment by randyaskin** [comment]
Fixed
