### ISSUE TITLE
Shadow dom support

### ISSUE THREAD

**Issue by davidsteinberger** [PredixDev/px-widget-cards#9]
Hi,

I just tried to use _px-threeup_ with shadow-dom. The flex-layout does not really seem to work.
Everything works fine with shady-dom.

## Expected behavior and actual behavior:

same layout behavior in shady- and shadow-dom

## Steps to reproduce the problem:

    // Setup Polymer options
    window.Polymer = {
    dom: 'shadow',
        lazyRegister: true,
    };

import and use px-widget-cards

## Environment (_component version number, Browser (including version), operating system, hardware, etc_):

- Polymer@v1.7.1
- px-widget-cards@2.2.1

**Comment by mdwragg** [comment]
Can you elaborate on how it doesn't work? Screenshots would be great!

cc/ @randyaskin - you might know if this is working or not, I can't see any differences between shady/shadow in the latest version (redesign).

**Comment by davidsteinberger** [comment]
I just tried the recent version and it seems to be working fine now. 

For clarity: can the dependency _eq.js_ be removed? Recent SASS/CSS does not seem to rely on it anymore and it does not seem to work with shadow dom anyhow.

**Comment by randyaskin** [comment]
Good catch. Removed in 3.0.2 (plus fixed some other wonkiness).
